version: '3.8'

services:
  postgres:
    image: postgres
    container_name: devnology-db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: devnology
    ports:
      - '5433:5432'


